source 'https://rubygems.org'
ruby '2.3.1'

gem 'uswds-jekyll', :git => 'https://github.com/18F/uswds-jekyll.git'
gem 'jekyll'
gem 'html-proofer'
gem 'pry'
gem 'hash-joiner'
gem 'json'
gem 'rb-readline'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
