source 'https://rubygems.org'
ruby '2.6.6'

gem 'uswds-jekyll', :git => 'https://github.com/18F/uswds-jekyll.git'
gem 'jekyll'
gem 'html-proofer'
gem 'pry'
gem 'hash-joiner'
gem 'json'
gem 'rb-readline'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'github-pages'
gem "jekyll-remote-theme"
gem 'jquery-smooth-scroll-rails', '~> 0.0.5'
