#!/usr/bin/env bash

title=$1
if [[ $1 && $1 != ' ' ]]; then
  FILE="pages/${title}.md"
  if [ -f $FILE ]; then
  echo "File already exists at ${FILE}"
  echo "Cannot overwrite file..."
  else
    touch $FILE
    up=$(tr '[:lower:]' '[:upper:]' <<< ${title:0:1})${title:1}
    # The following is the contents of the file that will be created
/bin/cat <<EOM >$FILE
---
layout: secondary
title: ${up}
permalink: /${title}/
---
EOM
  echo "New file created at ${FILE}!"
  echo "You can see this page at localhost:4000/${title}"
fi
else
  echo "No variable given"
  echo "..."
  echo "Syntax is new-page [name-of-file]"
fi
